# Generated by Django 3.1.1 on 2020-09-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='locking',
            field=models.BooleanField(default=False),
        ),
    ]
