# Generated by Django 3.1.1 on 2021-01-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0002_gear_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
