
name: Python Lint
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.x']
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install django-rest-framework django-rest-knox python-dotenv
          pip install pylint
      - name: Run linter
        run: pylint --rcfile=.pylintrc gearcatalog/**/*.py
